# Generated by Django 2.2.6 on 2019-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
