# Generated by Django 2.2.6 on 2019-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='homeImages')),
            ],
        ),
    ]
